name: Update ENTSO-E plots

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours (UTC)
  workflow_dispatch:        # enable manual run from Actions tab

permissions:
  contents: write           # allow this workflow to commit & push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true     # keep token for pushing
          fetch-depth: 0                # full history (safer for commits)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run plot generation
        env:
          ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
        run: |
          python main.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git diff --cached --quiet || git commit -m "Auto-update plots [skip ci]"
          git push